server:
  port: 9443
  ssl:
    enabled: true
    key-alias: tmssl
    key-store-password: tomcat123
    key-store: /var/microservices/tmssl.jks
    key-store-type: PKCS12
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"  
      discovery:
        locator:
          enabled: true
      routes:
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/email/**
        - id: sign-service
          uri: lb://sign-service
          predicates:
            - Path=/sign/**    
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**
        - id: cas-service
          uri: lb://cas-service
          predicates:
            - Path=/payment-decrees/**
        - id: alert-service
          uri: lb://alert-service
          predicates:
            - Path=/alerts/**
        - id: correlatives-service
          uri: lb://correlatives-service
          predicates:
            - Path=/correlative/**
        - id: document-template-service
          uri: lb://document-template-service
          predicates:
            - Path=/dpd-template/**
