server:
  port: 9443
  ssl:
    enabled: true
    key-alias: tmssl
    key-store-password: tomcat123
    key-store: /var/microservices/tmssl.jks
    key-store-type: PKCS12
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"  
      discovery:
        locator:
          enabled: true
      routes:
        - id: mail-service
          uri: lb://mail-service
          predicates:
            - Path=/email/**
        - id: sign-service
          uri: lb://sign-service
          predicates:
            - Path=/sign/**    
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**
        - id: officers
          uri: lb://officers
          predicates:
            - Path=/officers/**
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/** 
        - id: cas-service
          uri: lb://cas-service
          predicates:
            - Path=/payment-decrees/**
        - id: participants
          uri: lb://participants
          predicates:
            - Path=/participants/**,/history/**
        - id: prequalifiers
          uri: lb://prequalifiers
          predicates:
            - Path=/prequalifiers/**
        - id: qualification-stages
          uri: lb://qualification-stages
          predicates:
            - Path=/qualificationStages/**,/prequalifications/**,/firstEvaluation/**,/secondEvaluation/**
        - id: qualifications
          uri: lb://qualifications
          predicates:
            - Path=/qualifications/**,/appeals/**,/firstEvaluation/**,/ratifications/**
        - id: qualification-process
          uri: lb://qualification-process
          predicates:
            - Path=/qualifyingBoard/**,/process/**,/sessions/**    

